apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: productivity-tracker
type: Opaque
stringData:
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-base64"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: productivity-tracker
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "changeme"
